# Generated by Django 5.0.1 on 2026-02-02 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("uploads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "nid_number_hash",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("date_of_birth", models.DateField()),
                ("phone_verified", models.BooleanField(default=False)),
                ("residency_district", models.CharField(max_length=100)),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Enrollment"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citizen_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Citizen Profile",
                "verbose_name_plural": "Citizen Profiles",
                "db_table": "citizen_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_cases",
                        to="identity.citizenprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment Case",
                "verbose_name_plural": "Enrollment Cases",
                "db_table": "enrollment_cases",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("NID_FRONT", "NID Front"),
                            ("NID_BACK", "NID Back"),
                            ("SELFIE", "Selfie"),
                            ("PROOF", "Proof Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="identity.enrollmentcase",
                    ),
                ),
                (
                    "upload_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollment_documents",
                        to="uploads.uploadasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment Document",
                "verbose_name_plural": "Enrollment Documents",
                "db_table": "enrollment_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
