# Generated by Django 5.0.1 on 2026-02-02 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        help_text="List of allowed scopes: name_match, age_over_18, phone_verified, residency_district"
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_grants",
                        to="identity.citizenprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_grants",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Grant",
                "verbose_name_plural": "Consent Grants",
                "db_table": "consent_grants",
                "ordering": ["-granted_at"],
                "unique_together": {("citizen", "organization")},
            },
        ),
    ]
