# Generated by Django 5.0.1 on 2026-02-02 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.CharField(max_length=255, unique=True)),
                ("secure_url", models.URLField(max_length=500)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("raw", "Raw File"),
                            ("video", "Video"),
                        ],
                        max_length=50,
                    ),
                ),
                ("format", models.CharField(max_length=10)),
                ("bytes", models.IntegerField(help_text="File size in bytes")),
                ("checksum", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload Asset",
                "verbose_name_plural": "Upload Assets",
                "db_table": "upload_assets",
                "ordering": ["-created_at"],
            },
        ),
    ]
