# Generated by Django 5.0.1 on 2026-02-02 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="SUCCESS", max_length=20)),
                ("data_accessed", models.JSONField(default=dict)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_history",
                        to="identity.citizenprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_history",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "verification_history",
                "ordering": ["-verified_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_scopes", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="identity.citizenprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Request",
                "verbose_name_plural": "Verification Requests",
                "db_table": "verification_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_jti",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("scopes_disclosed", models.JSONField()),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_events",
                        to="identity.citizenprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="credentials.verificationrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Event",
                "verbose_name_plural": "Verification Events",
                "db_table": "verification_events",
                "ordering": ["-verified_at"],
            },
        ),
        migrations.CreateModel(
            name="AliasIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global Alias"),
                            ("PAIRWISE", "Pairwise Alias"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "alias_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="identity.citizenprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for pairwise aliases",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairwise_aliases",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias Identifier",
                "verbose_name_plural": "Alias Identifiers",
                "db_table": "alias_identifiers",
                "unique_together": {("citizen", "alias_type", "organization")},
            },
        ),
    ]
