# Generated by Django 5.0.1 on 2026-02-02 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ENROLLMENT_SUBMITTED", "Enrollment Submitted"),
                            ("ENROLLMENT_APPROVED", "Enrollment Approved"),
                            ("ENROLLMENT_REJECTED", "Enrollment Rejected"),
                            ("CONSENT_GRANTED", "Consent Granted"),
                            ("CONSENT_REVOKED", "Consent Revoked"),
                            ("VERIFICATION_REQUESTED", "Verification Requested"),
                            ("VERIFICATION_APPROVED", "Verification Approved"),
                            ("VERIFICATION_DENIED", "Verification Denied"),
                            ("VERIFICATION_COMPLETED", "Verification Completed"),
                            ("ALIAS_GENERATED", "Alias Generated"),
                            ("ALIAS_ROTATED", "Alias Rotated"),
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("OTHER", "Other Event"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Event-specific data"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "db_table": "audit_events",
                "ordering": ["-created_at"],
                "permissions": [("view_audit", "Can view audit logs")],
            },
        ),
    ]
